### ISSUE TITLE
hanging on long domain with double dots inside

### ISSUE THREAD

**Issue by nitr0man** [python-validators/validators#269] opened 2023-04-20 14:10 UTC
validators-0.20.0 hangs on long domain with 2 consequent dots

```
In [2]: validators.url('http://a.b.c.d.e..com/')
Out[2]: ValidationFailure(func=url, args={'value': 'http://a.b.c.d.e..com/', 'public': False})

In [3]: validators.url('http://www.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc.dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..com')
^C---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-3-96130bac0982> in <cell line: 1>()
----> 1 validators.url('http://www.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc.dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..com')

~/.virtualenvs/pbn/lib/python3.8/site-packages/decorator.py in fun(*args, **kw)
    230             if not kwsyntax:
    231                 args, kw = fix(args, kw, sig)
--> 232             return caller(func, *(extras + args), **kw)
    233     fun.__name__ = func.__name__
    234     fun.__doc__ = func.__doc__

~/.virtualenvs/pbn/lib/python3.8/site-packages/validators/utils.py in wrapper(func, *args, **kwargs)
     77     """
     78     def wrapper(func, *args, **kwargs):
---> 79         value = func(*args, **kwargs)
     80         if not value:
     81             return ValidationFailure(

~/.virtualenvs/pbn/lib/python3.8/site-packages/validators/url.py in url(value, public)
    146     :param public: (default=False) Set True to only allow a public IP address
    147     """
--> 148     result = pattern.match(value)
    149     if not public:
    150         return result
```

**Comment by joe733** [comment] 2023-04-20 15:36
This as been taken care of in #245.

Duplicate of #65

Ref #267, #268

![Screenshot_2023-04-20-21-01-59-783_com.termux.jpg](https://user-images.githubusercontent.com/38415384/233416464-42b4767b-d9bf-4bca-af91-1c8b9ec188c1.jpg)

**Closed** 2023-04-20 15:37 UTC
Labels: duplicate
