### ISSUE TITLE
A valid url produces ValidationFailure

### ISSUE THREAD

**Issue by oakkitten** [python-validators/validators#116] opened 2019-03-04 10:22 UTC
https://xn----8sbfxoeboc6b7i.xn--p1ai

    validators.url("https://xn----8sbfxoeboc6b7i.xn--p1ai")
    ValidationFailure(func=url, args={'value': 'https://xn----8sbfxoeboc6b7i.xn--p1ai', 'public': False})

**Comment by Marcussk** [comment] 2019-04-02 06:51
This Issue is duplicate of #87.

**Closed** 2023-03-18 08:33 UTC
Labels: bug, duplicate, outdated
